//Phim đang chiếu
export const MOVIE_NOW_REQUEST = "MovieNowReducer/MOVIE_NOW_REQUEST";
export const MOVIE_NOW_SUCCESS = "MovieNowReducer/MOVIE_NOW_SUCCESS";
export const MOVIE_NOW_FAILED = "MovieNowReducer/MOVIE_NOW_FAILED";
//Phim Sắp chiếu
export const MOVIE_SOON_REQUEST = "MovieSoonReducer/MOVIE_SOON_REQUEST";
export const MOVIE_SOON_SUCCESS = "MovieSoonReducer/MOVIE_SOON_SUCCESS";
export const MOVIE_SOON_FAILED = "MovieSoonReducer/MOVIE_SOON_FAILED";

export const GET_MOVIES = "GET-MOVIES";
export const SHOW_MOVIES = "SHOW_MOVIES";

export const GET_HE_THONG = "GET_HE_THONG";
export const GET_MOVIES_HT = "GET_MOVIES_HT";
export const GET_CHI_TIET_HE_THONGS = "GET_CHI_TIET_HE_THONGS";
export const CHANGE_HE_THONG = "CHANGE_HE_THONG";
export const CHANGE_DANH_SACH_PHIM = "CHANGE_DANH_SACH_PHIM";

export const CHANGEYOUTUBE = "CHANGEYOUTUBE";
export const LICHCHIEUPHIMCHITIET = "LICHCHIEUPHIMCHITIET";
export const CHANGELOADING = "CHANGELOADING";
export const CHANGEHETHONGCTP = "CHANGEHETHONGCTP";
export const CHANGERAPCHIEU = "CHANGERAPCHIEU";
export const INITLICHCHIETCTP = "INITLICHCHIETCTP";
export const GET_DANHSACHPHONGVE = "GET_DANHSACHPHONGVE";
export const CHANGELOADINGRAPCHIEU = "CHANGELOADINGRAPCHIEU";
export const CHANGELOADINGCTP = "CHANGELOADINGCTP";

export const ADDGHE = "ADDGHE";
export const REMOVEGHE = "REMOVEGHE";

export const CHANGECOMBO = "CHANGECOMBO";

export const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const FETCH_CINEMA = "FETCH_CINEMA";
export const FETCH_CINEMA_GROUP = "FETCH_CINEMA_GROUP";

export const FETCH_TICKET_ROOM_REQUEST =
  "BookingTicket/FETCH_TICKET_ROOM_REQUEST";
export const FETCH_TICKET_ROOM_SUCCESS =
  "BookingTicket/FETCH_TICKET_ROOM_SUCCESS";
export const FETCH_TICKET_ROOM_FAILURE =
  "BookingTicket/FETCH_TICKET_ROOM_FAILURE";

export const PUSH_SEAT = "BookingTicket/PUSH_SEAT";

export const CHANGE_COMBO_NUMBER = "BookingTicket/CHANGE_COMBO_NUMBER";

export const BOOK_TICKET_REQUEST = "BookingTicket/BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BookingTicket/BOOK_TICKET_SUCCESS";
export const BOOK_TICKET_FAIL = "BookingTicket/BOOK_TICKET_FAIL";
