export const LAYTHONGTINLICH_REQUEST = "CinemaReducer/LAYTHONGTINLICH_REQUEST";
export const LAYTHONGTINLICH_SUCCESS = "CinemaReducer/LAYTHONGTINLICH_SUCCESS";
export const LAYTHONGTINLICH_FAILED = "CinemaReducer/LAYTHONGTINLICH_FAILED";
