export const MOVIE_SCHEDULE_REQUEST = "DetailMovieItem/MOVIE_SCHEDULE_REQUEST";
export const MOVIE_SCHEDULE_SUCCESS = "DetailMovieItem/MOVIE_SCHEDULE_SUCCESS";
export const MOVIE_SCHEDULE_FAILED = "DetailMovieItem/MOVIE_SCHEDULE_FAILED";
