export const DETAIL_LISTMOVIE_REQUEST = "MovieReducer/DETAIL_LISTMOVIE_REQUEST";
export const DETAIL_LISTMOVIE_SUCCESS = "MovieReducer/DETAIL_LISTMOVIE_SUCCESS";
export const DETAIL_LISTMOVIE_FAILED = "MovieReducer/DETAIL_LISTMOVIE_FAILED";

export const GET_KEYWORD_LISTMOVIE = "MovieReducer/GET_KEYWORD_LISTMOVIE";

export const DELETE_MOVIE = "MovieReducer/DELETE_MOVIE"