export const DETAIL_LISTMOVIE_REQUEST = "DetailListMovieReducer/DETAIL_LISTMOVIE_REQUEST";
export const DETAIL_LISTMOVIE_SUCCESS = "DetailListMovieReducer/DETAIL_LISTMOVIE_SUCCESS";
export const DETAIL_LISTMOVIE_FAILED = "DetailListMovieReducer/DETAIL_LISTMOVIE_FAILED";

export const GET_KEYWORD_LISTMOVIE = "DetailListMovieReducer/GET_KEYWORD_LISTMOVIE";

export const ADD_DETAIL_LISTMOVIE_REQUEST = "DetailListMovieReducer/ADD_DETAIL_LISTMOVIE_REQUEST"
export const ADD_DETAIL_LISTMOVIE_SUCCESS = "DetailListMovieReducer/ADD_DETAIL_LISTMOVIE_SUCCESS"
export const ADD_DETAIL_LISTMOVIE_FAILED = "DetailListMovieReducer/ADD_DETAIL_LISTMOVIE_FAILED"

export const EDIT_MOVIE = "AddListMovieReducer/EDIT_DETAIL_LISTMOVIE";
